[versions]
leafplugin = "1.0.0"
servlet = "4.0.4"

[libraries]
leafagent = { group = "leafagent", name = "agent", version.ref = "leafplugin" }
servlet = { group = "jakarta.servlet", name = "jakarta.servlet-api", version.ref = "servlet" }

[plugins]